server:
  port: 1002
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eurekaslave
  client:
#    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone: http://eurekamaster:1001/eureka
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 4000
