server:
  port: 3001
spring:
  application:
    name: microservice-client
  zipkin:
    base-url: http://locahost:4001
    enabled: true
management:
  context-path: /client
eureka:
  client:
    service-url:
      defaultZone: http://eurekamaster:1001/eureka,http://eurekaslave:1001/eureka
  instance:
    status-page-url-path: ${management.context-path}/info

zuul:
  routes:
    users:
      path: /api/**
      serviceId: one-service

#取消验证
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

